project:
  type: website
  output-dir: docs

website:
  title: "Moak-s"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: SASIE
        href: SASIE.qmd 
      - text: Tutorial
        href: tutorial.qmd  
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: arial
    fontsize: 1.0rem
    css: styles.css
    toc: true

editor: visual

